apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onav-data
spec:
  storageClassName: ocs-external-storagecluster-cephfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

