apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ocnav-dev-build
  namespace: proj-k8s-ssc-hpco
  labels:
    name: ocnav-dev-build
spec:
  source:
    type: Git
    contextDir: "docker/dev"
    git:
      ref: docker
      uri: "https://github.com/tripougnif/Ocean-Data-Map-Project.git"
  strategy:
    type: Docker
  resources:
    limits:
      cpu: '4'
      memory: 8Gi
  output:
    to:
      type: imageStreamTag
      name: "ocnav-dev:latest"
